global.settings = {
    OWNER_NUMBERS: "916282524515", // replace with your number
    OWNER_NAME: ' ᴀɴsʜɪғ xᴇʀ', // desired name
    BOT_NAME: "ᴀɴsʜɪғ xᴇʀ", // desired name
    VERSION: 'V1.0.0',
    SESSION_ID: 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUcyOUFteGp0ZjRSSmcvbXZ3SEJBN2w4enBrN1AxQzQyMUZqTDRudFcxST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY3I3SkFGN0VSMkZIRGt6bVNBYjl5V0V0TjFodER1ak1EV2c1aUJnV1pHaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBTGc1TmFCTUlMcGRaVG5XQ2gzNXZBSzVaYnZIZTEwSG1ZbkNyUlpDaW53PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIvTS9ZYm40aW1PZGYvZnRKYmFJWWFzQlFoNEVDVThtTDlVd3llNURFcVU4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjROUTIzaFRuOXZlY2pDNURaUzlLOXdTT0tPQkp6dlNMMDlzaUFJcU5YMzQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhRMkxWeWpwVmlKTCtWamU0TUdSYXBlVGNNZXFjWld2OEFPZ3E3b2RXMHc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUhmeHRDVE1aVk01OExkQWRVMU9CeUtVbm1jdU85R0pxeWsyVWl3NHBucz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMVZhY0VUZzlNeTJ1cit2a3ZaNWNpRmJ3dG95T292aDMvRStwV2NYN3l6MD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iit6aUgwbHVPLzhXWU4yUk9MWWN6YVJnVFVnbjA2b0NNYmpOd2NCMlNvSXFmVGJSOHdGRTMyUXJuVUdyNURPWlUxQzljaWxFSkxIbjNIb0hpeXNZRGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTcxLCJhZHZTZWNyZXRLZXkiOiJ6cWNZN0d6VzdUa1BjUE9XajlRYVYwUXlRcXZOL0JaQmYwemdrNnVGM2hBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJHMUtDNXh1QVNIdWhneE1nY1IzUkR3IiwicGhvbmVJZCI6IjBkMjgxZDYzLThlNWEtNDZjZS05ZTgxLTg5NGViMzFhYjQzMiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJKamcwM3FJMzNpdnk0U0VHOUh2ZEdyeDJaWVk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMGR3QkU1N2RRajNVN2x6NVdrTE92Q0lBUjlvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Iks3OTczR0pIIiwibWUiOnsiaWQiOiI5MTYyODI1MjQ1MTU6OTZAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ01uUHdkUUZFUGlpMDdnR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjVvU2psQWt0dVorVWtsUDVsdm80cVJXODk5azNCWjFSQUk1TElRYWdVRWs9IiwiYWNjb3VudFNpZ25hdHVyZSI6Ik9yZm5HeXRvN2dkVVlCNmdRblV2Vm8vNEh1S2VEbUMxVTBpNzFMS2ZWNGNZU0Nla0lsektNaTk2NHpOZ2tEV214elZQL2NJTi8zZEpGWVJKa0ZNbEN3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJkQnFyYS9zRGJ5eHBEZDBKTDliT3pLQnlZT0h0dHlUSHRWbWZrT1ByWHdIN0l4aEZrckdvY3JvUXJTcHBtSnUyWnQxWEtvSnFLVGk5RmZJU1U5a2hqZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkxNjI4MjUyNDUxNTo5NkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJlYUVvNVFKTGJtZmxKSlQrWmI2T0trVnZQZlpOd1dkVVFDT1N5RUdvRkJKIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI5NDE3NjA1LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU56NiJ9==', //put your session id between ''
    MONGO_DB_URL: 'mongodb+srv://miracle32669:Iyanu1234@cluster0.m7glm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0',
    WORK_MODE: "Public",
    READ_ALL_MESSAGES: false,
    PREFIX: [".", "/", "!"],
    WELCOME_MESSAGE: "Hello! I'm  ᴀɴsʜɪғ xᴇʀ, your friendly WhatsApp bot.",
    DEFAULT_TRANSLATION_LANG: "en",
    COMMAND_COOLDOWN_TIME_IN_MS: 2000,
    MAX_COMMANDS_PER_MINUTE: 10,
    MAX_DOWNLOAD_SIZE: 100,
    API_KEYS: {
        OPENWEATHERMAP_API_KEY: ''
    },
    isHackEnable:true,
    SAFE_SEARCH: true,
    REJECT_CALLS: true,
    SEND_WELCOME_MESSAGE: false,
    WELCOME_MESSAGE: "👋 Welcome to the group! We're glad to have you here.IM  ᴀɴsʜɪғ xᴇʀ 😊",
    DELETE_WA_LINKS: false,
    BAD_WORD_FILTER: true,
    BAD_WORDS: ['badword1', 'badword2', 'fuck', 'bitch', 'hentai'],
    ANTI_DELETE_ENABLED: true // Add this line for anti-delete feature
};
